version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Build
          command: cargo build
workflows:
  version: 2
  build:
    jobs:
      - build
